#!/bin/bash

echo "# i love you #" >> ~/.bashrc

echo "i=\`hostname -I | awk '{print\$1}'\`" >> ~/.bashrc

echo "export ROS_MASTER_URI=http://\$i:11311" >> ~/.bashrc
echo "export ROS_HOSTNAME=\$i" >> ~/.bashrc
echo "export ROS_IP=\$i" >> ~/.bashrc




