#!/bin/bash

sudo apt install -y ros-kinetic-turtlebot-description
sudo apt install -y ros-kinetic-robot-state-publisher
sudo apt install -y ros-kinetic-gmapping
sudo apt install -y python-serial
sudo usermod -aG dialout rosmm

